// Checks the pointer-shape decoder against hand-computed expectations.
//
// The three Windows cursor formats are a specification, not an algorithm we
// chose, so the expectations here are written out by hand from that spec
// rather than generated by a second implementation of the same guess.

#include "CursorDecoder.h"

#include <cstdio>
#include <vector>

using namespace visual4k;

namespace {

int failures = 0;

void Check(bool condition, const char* what)
{
    std::printf("%-58s %s\n", what, condition ? "ok" : "FAIL");
    if (!condition) ++failures;
}

struct Px { uint8_t r, g, b, a, invert; };

Px At(const DecodedCursor& c, uint32_t x, uint32_t y)
{
    const size_t i = static_cast<size_t>(y) * c.width + x;
    return {c.rgba[i * 4], c.rgba[i * 4 + 1], c.rgba[i * 4 + 2],
            c.rgba[i * 4 + 3], c.invert[i]};
}

bool Same(Px a, Px b)
{
    return a.r == b.r && a.g == b.g && a.b == b.b && a.a == b.a &&
           a.invert == b.invert;
}

void TestMonochrome()
{
    std::printf("\n-- monochrome (AND/XOR stacked, 1 bit per pixel) --\n");

    // 8x2 cursor => an 8x4 buffer: two rows of AND, then two rows of XOR.
    // Column 0..3 of row 0 exercise all four AND/XOR combinations:
    //   AND XOR  result
    //    0   0   opaque black
    //    0   1   opaque white
    //    1   0   transparent
    //    1   1   invert the screen
    // Bits are most-significant-first, so column 0 is bit 0x80.
    const uint8_t andBits = 0b00110000;   // cols 0,1 = 0 ; cols 2,3 = 1
    const uint8_t xorBits = 0b01010000;   // cols 0,2 = 0 ; cols 1,3 = 1

    std::vector<uint8_t> buf = {andBits, andBits, xorBits, xorBits};
    const auto c = DecodePointerShape(PointerShapeType::Monochrome, buf.data(),
                                      buf.size(), 8, 4, 1);

    Check(c.width == 8 && c.height == 2, "reported height is halved");
    Check(Same(At(c, 0, 0), {0, 0, 0, 255, 0}),     "AND=0 XOR=0 is opaque black");
    Check(Same(At(c, 1, 0), {255, 255, 255, 255, 0}), "AND=0 XOR=1 is opaque white");
    Check(Same(At(c, 2, 0), {0, 0, 0, 0, 0}),       "AND=1 XOR=0 is transparent");
    Check(Same(At(c, 3, 0), {0, 0, 0, 0, 255}),     "AND=1 XOR=1 inverts the screen");
    Check(Same(At(c, 0, 1), At(c, 0, 0)),           "second row decodes identically");
}

void TestColor()
{
    std::printf("\n-- colour (straight BGRA) --\n");

    // Two pixels: opaque red, then half-transparent blue. Source is BGRA.
    std::vector<uint8_t> buf = {
        0x00, 0x00, 0xFF, 0xFF,     // B=0 G=0 R=255 A=255
        0xFF, 0x00, 0x00, 0x80,     // B=255 G=0 R=0 A=128
    };
    const auto c = DecodePointerShape(PointerShapeType::Color, buf.data(),
                                      buf.size(), 2, 1, 8);

    Check(c.width == 2 && c.height == 1, "geometry is passed through");
    Check(Same(At(c, 0, 0), {255, 0, 0, 255, 0}), "BGRA is reordered to RGBA");
    Check(Same(At(c, 1, 0), {0, 0, 255, 128, 0}), "alpha is preserved");
    Check(At(c, 0, 0).invert == 0 && At(c, 1, 0).invert == 0,
          "colour cursors never invert");
}

void TestMaskedColor()
{
    std::printf("\n-- masked colour (alpha is a flag, not coverage) --\n");

    std::vector<uint8_t> buf = {
        0x00, 0xFF, 0x00, 0x00,     // green, alpha 0   -> draw opaque
        0x00, 0x00, 0xFF, 0xFF,     // red,   alpha 255 -> XOR with screen
    };
    const auto c = DecodePointerShape(PointerShapeType::MaskedColor, buf.data(),
                                      buf.size(), 2, 1, 8);

    Check(Same(At(c, 0, 0), {0, 255, 0, 255, 0}), "alpha 0 becomes fully opaque");
    Check(Same(At(c, 1, 0), {255, 0, 0, 0, 255}), "alpha 255 becomes an invert");
}

void TestBounds()
{
    std::printf("\n-- refuses to read past the buffer --\n");

    std::vector<uint8_t> tiny = {0x00, 0x00};

    Check(DecodePointerShape(PointerShapeType::Color, tiny.data(), tiny.size(),
                             64, 64, 256).Empty(),
          "undersized colour buffer returns empty");
    Check(DecodePointerShape(PointerShapeType::Monochrome, tiny.data(),
                             tiny.size(), 32, 64, 4).Empty(),
          "undersized monochrome buffer returns empty");
    Check(DecodePointerShape(PointerShapeType::Color, nullptr, 0, 32, 32, 128)
              .Empty(),
          "null buffer returns empty");
    Check(DecodePointerShape(PointerShapeType::Color, tiny.data(), tiny.size(),
                             0, 32, 128).Empty(),
          "zero width returns empty");

    // A 1-pixel-tall monochrome shape has no room for both masks.
    std::vector<uint8_t> one = {0xFF};
    Check(DecodePointerShape(PointerShapeType::Monochrome, one.data(),
                             one.size(), 8, 1, 1).Empty(),
          "monochrome shorter than two masks returns empty");
}

}  // namespace

int main()
{
    TestMonochrome();
    TestColor();
    TestMaskedColor();
    TestBounds();

    std::printf("\n%s\n", failures == 0 ? "all cursor decode checks passed"
                                        : "CURSOR DECODE SELF-TEST FAILED");
    return failures == 0 ? 0 : 1;
}
